-- CREATE DATABASE IF NOT EXISTS campusx;
-- USE campusx;
-- CREATE TABLE
CREATE TABLE users(
userid INTEGER PRIMARY KEY auto_increment,
name VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL
);
-- INSERT DATA
INSERT INTO campusx.users (password,email,name)
VALUES(123456,'Aryan@21','Aryan75');

-- RETERIVE DATA FROM TABLE
SELECT * FROM users;

-- INSERT MULTIPLE RECORDS WITH SPECIFIED ORDER
INSERT INTO campusx.users (password,email,name)
VALUES(123456,'Arman@21','Arman75'),
('rahul31','RAHUL@123','RAHUL RAJPUT'),
('RAJ27','RAJ@123','RAJ PATWA');

-- FETCH ALL THE ROWS AND COLS FROM TABLE
SELECT * FROM campusx.smartphones
WHERE 1; -- (OPTIONAL)

-- FILTER COLUMNS
SELECT MODEL,PRICE,RATING FROM SMARTPHONES;

SELECT MODEL, BATTERY_CAPACITY, OS FROM SMARTPHONES;

-- ALIASING:- CHANGING NAME OF COLUMNS
SELECT MODEL, BATTERY_CAPACITY AS BATTERY_MAH, OS AS OPERATING_SYSTEM FROM CAMPUSX.SMARTPHONES;

SELECT MODEL, SQRT(RESOLUTION_WIDTH*RESOLUTION_WIDTH + RESOLUTION_HEIGHT*RESOLUTION_HEIGHT)/SCREEN_SIZE AS PPI FROM SMARTPHONES
ORDER BY PPI;

SELECT MODEL, RATING/10 FROM SMARTPHONES;

-- CONSTANTS
SELECT MODEL, 'SMARTPHONE' AS 'TYPE' FROM SMARTPHONES;

-- DISTINCT (UNIQUE)
SELECT DISTINCT(BRAND_NAME) AS 'ALL BRANDS' FROM SMARTPHONES;
SELECT DISTINCT(PROCESSOR_BRAND) AS 'ALL_PROCESSOR_BRAND' FROM SMARTPHONES;
SELECT DISTINCT(OS) AS 'ALL_OS' FROM SMARTPHONES;

-- DISTINCT COMBINATION
SELECT DISTINCT BRAND_NAME, PROCESSOR_BRAND AS 'PROCESSOR' FROM SMARTPHONES;

-- WHERE USED TO FILTER ROWS
SELECT * FROM SMARTPHONES
WHERE BRAND_NAME = 'SAMSUNG';

SELECT * FROM SMARTPHONES
WHERE PRICE>50000;


-- BETWEEN
SELECT * FROM SMARTPHONES
WHERE PRICE BETWEEN 10000 AND 20000;

-- AND
SELECT * FROM SMARTPHONES
WHERE RATING > 80 AND PRICE < 25000;

SELECT * FROM SMARTPHONES
WHERE PRICE<15000 AND RATING > 80 AND PROCESSOR_BRAND = 'SNAPDRAGON';

SELECT * FROM SMARTPHONES
WHERE BRAND_NAME = 'SAMSUNG' AND RAM_CAPACITY > 8; 

SELECT * FROM SMARTPHONES
WHERE BRAND_NAME = 'SAMSUNG' AND PROCESSOR_BRAND = 'SNAPDRAGON';

SELECT DISTINCT BRAND_NAME FROM SMARTPHONES
WHERE PRICE>100000;

-- IN AND NOT IN
SELECT * FROM SMARTPHONES
WHERE PROCESSOR_BRAND IN ('SNAPDRAGON','BIONIC','EXYNOS');


SELECT * FROM SMARTPHONES
WHERE PROCESSOR_BRAND NOT IN ('SNAPDRAGON','BIONIC','EXYNOS');

-- UPDATE

SET SQL_SAFE_UPDATES = 0; -- TURNS SAFE MODE OFF

UPDATE SMARTPHONES
SET PROCESSOR_BRAND = 'MEDIATEK'
WHERE PROCESSOR_BRAND = 'DIMENSITY';

SELECT * FROM SMARTPHONES
WHERE PROCESSOR_BRAND = 'MEDIATEK'; 

SET SQL_SAFE_UPDATES = 1; -- TURNS SAFE MODE ON

SELECT * FROM USERS;

-- UPDATE MULTIPLE COLUMNS OR ATTRIBUTES
UPDATE USERS
SET EMAIL = 'AMAAN@1234',
    PASSWORD = 'AMAAN1234'
WHERE NAME = 'AMAAN';

-- DELETE

-- Q1 DELETE SMARTPHONES WITH PRICE GREATER THAN 200000
SELECT * FROM SMARTPHONES
WHERE PRICE>200000;

DELETE FROM SMARTPHONES
WHERE PRICE>200000;
-- Q2 DELETE PHONES WITH REAR_CAMERA > 150 AND BRAND_NAME = SAMSUNG
SELECT * FROM SMARTPHONES
WHERE PRIMARY_CAMERA_REAR > 150 AND BRAND_NAME = 'SAMSUNG';

DELETE FROM SMARTPHONES
WHERE PRIMARY_CAMERA_REAR > 150 AND BRAND_NAME = 'SAMSUNG';

-- Agregate functions
SELECT MAX(PRICE) FROM SMARTPHONES;

SELECT MIN(PRICE) FROM SMARTPHONES;

SELECT MAX(PRICE) FROM SMARTPHONES
WHERE BRAND_NAME = 'SAMSUNG';

SELECT AVG(RATING) FROM SMARTPHONES
WHERE BRAND_NAME = 'APPLE';

SELECT SUM(PRICE) FROM SMARTPHONES;

SELECT COUNT(*) FROM SMARTPHONES
WHERE BRAND_NAME = 'SAMSUNG';

SELECT COUNT(DISTINCT(BRAND_NAME)) AS NUMBER_OF_BRAND FROM SMARTPHONES;

SELECT COUNT(DISTINCT(PROCESSOR_BRAND)) AS NUMBER_OF_BRAND FROM SMARTPHONES;

SELECT STD(SCREEN_SIZE) FROM SMARTPHONES;

SELECT VARIANCE(SCREEN_SIZE) FROM SMARTPHONES;

-- SCALAR FUNCTIONS

SELECT PRICE - 100000 AS TEMP FROM SMARTPHONES;

SELECT ABS(PRICE - 100000) AS TEMP FROM SMARTPHONES;

SELECT MODEL, ROUND(SQRT(RESOLUTION_WIDTH*RESOLUTION_WIDTH + RESOLUTION_HEIGHT*RESOLUTION_HEIGHT)/SCREEN_SIZE,2) AS PPI FROM SMARTPHONES
ORDER BY PPI;

SELECT SCREEN_SIZE FROM SMARTPHONES;

SELECT CEIL(SCREEN_SIZE) FROM SMARTPHONES;

SELECT FLOOR(SCREEN_SIZE) FROM SMARTPHONES;










