use campusx;

SELECT * FROM SMARTPHONES;

-- ORDER BY

SELECT MODEL,SCREEN_SIZE FROM SMARTPHONES
WHERE BRAND_NAME = 'SAMSUNG'
ORDER BY SCREEN_SIZE DESC
LIMIT 5;

SELECT MODEL, NUM_REAR_CAMERAS + NUM_FRONT_CAMERAS AS 'TOTAL_CAMERAS' FROM SMARTPHONES
ORDER BY TOTAL_CAMERAS DESC ;


SELECT MODEL, ROUND(SQRT(RESOLUTION_HEIGHT * RESOLUTION_HEIGHT + RESOLUTION_WIDTH * RESOLUTION_WIDTH) / SCREEN_SIZE	) AS PPI FROM SMARTPHONES
ORDER BY PPI DESC;

SELECT MODEL, BATTERY_CAPACITY FROM SMARTPHONES
ORDER BY BATTERY_CAPACITY DESC LIMIT 1,1;

SELECT MODEL, BATTERY_CAPACITY FROM SMARTPHONES
ORDER BY BATTERY_CAPACITY ASC LIMIT 1,1;

SELECT MODEL,RATING FROM SMARTPHONES
WHERE BRAND_NAME = 'APPLE'
ORDER BY RATING  LIMIT 1;

-- SORTING TWO COLUMNS TOGETHER
SELECT * FROM SMARTPHONES
ORDER BY BRAND_NAME, PRICE; 

SELECT * FROM SMARTPHONES
ORDER BY BRAND_NAME ASC, RATING DESC;

-- GROUP BY

SELECT UPPER(BRAND_NAME), COUNT(*) AS NUM_PHONES, AVG(PRICE), MAX(RATING), AVG(SCREEN_SIZE), AVG(BATTERY_CAPACITY) FROM SMARTPHONES
GROUP BY BRAND_NAME
ORDER BY NUM_PHONES DESC;

SELECT HAS_NFC, AVG(PRICE), AVG(RATING) FROM SMARTPHONES
GROUP BY HAS_NFC;

SELECT HAS_5G, AVG(PRICE), AVG(RATING) FROM SMARTPHONES
GROUP BY HAS_5G;

SELECT FAST_CHARGING_AVAILABLE, AVG(PRICE), AVG(RATING) FROM SMARTPHONES
GROUP BY FAST_CHARGING_AVAILABLE;

SELECT EXTENDED_MEMORY_AVAILABLE, AVG(PRICE), AVG(RATING) FROM SMARTPHONES
GROUP BY EXTENDED_MEMORY_AVAILABLE;

SELECT UPPER(BRAND_NAME), PROCESSOR_BRAND, COUNT(*) AS 'COUNT', AVG(PRIMARY_CAMERA_REAR), AVG(PRIMARY_CAMERA_FRONT) FROM SMARTPHONES
GROUP BY BRAND_NAME, PROCESSOR_BRAND
ORDER BY BRAND_NAME;

SELECT UPPER(BRAND_NAME), AVG(PRICE) FROM SMARTPHONES
GROUP BY BRAND_NAME
ORDER BY AVG(PRICE) DESC LIMIT 5;

SELECT UPPER(BRAND_NAME), AVG(SCREEN_SIZE) FROM SMARTPHONES
GROUP BY BRAND_NAME
ORDER BY AVG(SCREEN_SIZE) ASC LIMIT 1;

SELECT HAS_5G, AVG(PRICE) FROM SMARTPHONES
GROUP BY HAS_5G;

SELECT UPPER(BRAND_NAME),HAS_NFC,HAS_IR_BLASTER, COUNT(*) AS 'NUM_OF_MODELS' FROM SMARTPHONES
WHERE HAS_NFC = 'TRUE' AND HAS_IR_BLASTER = 'TRUE'
GROUP BY BRAND_NAME
ORDER BY NUM_OF_MODELS DESC LIMIT 1;

SELECT UPPER(BRAND_NAME),HAS_NFC,AVG(PRICE) FROM SMARTPHONES
WHERE HAS_5G = 'TRUE' AND BRAND_NAME = 'SAMSUNG'
GROUP BY HAS_NFC;

SELECT MODEL, PRICE FROM SMARTPHONES
ORDER BY PRICE DESC LIMIT 1;

SELECT UPPER(BRAND_NAME),COUNT(*) AS 'NUM_OF_MODELS',  AVG(RATING) FROM SMARTPHONES
GROUP BY BRAND_NAME
HAVING NUM_OF_MODELS>=20
ORDER BY AVG(RATING) DESC;

SELECT UPPER(BRAND_NAME),COUNT(*) AS 'NUM_MODELS', AVG(RAM_CAPACITY) FROM SMARTPHONES
WHERE REFRESH_RATE >= 90 AND FAST_CHARGING_AVAILABLE = 1
GROUP BY BRAND_NAME
HAVING NUM_MODELS >= 10
ORDER BY AVG(RAM_CAPACITY) DESC LIMIT 3;

SELECT UPPER(BRAND_NAME) AS 'BRAND', ROUND(AVG(PRICE),2) AS 'AVG_PRICE' FROM SMARTPHONES
WHERE HAS_5G = 'TRUE'
GROUP BY BRAND_NAME
HAVING AVG(RATING)>70 AND COUNT(*)>10
ORDER BY AVG(PRICE) DESC ;

SELECT * FROM SMARTPHONES;









