-- # CREATING A DATABASE
-- -- create database CodeWithHarry;

-- # USNING A DATABASE
-- -- use codewithharry;

-- # CREATING A TABLE
-- -- CREATE TABLE Users(ID INT auto_increment PRIMARY KEY,NAME VARCHAR(100) NOT NULL,SALARY INT,EMAIL VARCHAR(100));

-- # RETRIVEING EVERYTHING
-- -- SELECT * FROM USERS;

-- # RENAMING A TABLE
-- # RENAME TABLE USERS TO PROGRAMMERS;

-- # RENAME TABLE PROGRAMMERS TO USERS;
-- # SELECT * FROM USERS;

-- # ALTERING A TABLE
-- # 1. ADDING A COLUMN  
-- -- ALTER TABLE USERS ADD  COLUMN CREATED timestamp DEFAULT current_timestamp;
-- -- SELECT * FROM USERS;
-- # 2. DROPPING(DELETING) A COLUMN
-- -- ALTER TABLE USERS DROP COLUMN IS_ACTIVE;
-- -- SELECT * FROM USERS;
-- # MODIFY A TABLE
-- # 1. MODIFYING A COLUMN
-- # ALTER TABLE USERS MODIFY COLUMN NAME varchar(150);
-- # 2. MODIFY A COLUMN'S POSITION
-- -- ALTER TABLE USERS MODIFY COLUMN SALARY INT AFTER NAME;
-- -- SELECT * FROM USERS;

-- # INSERT QUERY
-- INSERT INTO USERS(NAME,SALARY,EMAIL,CREATED) VALUES
-- ("ZAYN",55000,'ZAYN@GMAIL.COM',DEFAULT),
-- ("ROHAN",22000,'ROHAN@GMAIL.COM',DEFAULT),
-- ("SURESH",34000,'SURESH@GMAIL.COM',DEFAULT),
-- ("TONY",48000,'TONY@GMAIL.COM',DEFAULT);
-- SELECT * FROM USERS;
