-- OUTER JOIN
SELECT * FROM person1 AS T1
LEFT JOIN person2 AS T2
ON T1.ID = T2.ID
UNION
SELECT * FROM person1 AS T1
RIGHT JOIN person2 AS T2
ON T1.ID = T2.ID;

SELECT * FROM person1 AS T1
LEFT JOIN person2 AS T2
ON T1.ID = T2.ID
UNION ALL
SELECT * FROM person1 AS T1
RIGHT JOIN person2 AS T2
ON T1.ID = T2.ID;