-- FIND USER_ID WHO NEVER ORDERED
SELECT * FROM USERS
WHERE USER_ID NOT IN (SELECT USER_ID FROM ORDERS);

SELECT * FROM MOVIES;
-- SELECT MOVIES OF TOP DIRECTORS WITH HIGHEST GROSS
SELECT * FROM MOVIES
WHERE DIRECTOR IN (SELECT DISTINCT DIRECTOR FROM MOVIES
					WHERE GROSS IN (SELECT GROSS FROM MOVIES
						ORDER BY GROSS DESC
                        LIMIT 3)
                        );
-- SAME QUESTION WITH CTE  
WITH TOP_DIRECTORS AS (SELECT DIRECTOR FROM MOVIES
GROUP BY DIRECTOR
ORDER BY SUM(GROSS) DESC
LIMIT 3)

SELECT * FROM MOVIES
WHERE DIRECTOR IN (SELECT * FROM TOP_DIRECTORS)
ORDER BY DIRECTOR;

-- FIND MOVIES OF ACTORS WITH AVG RATING OF MORE THAN 8.5 AND VOTES GREATER THAN 25000

SELECT * FROM MOVIES
WHERE STAR IN (SELECT DISTINCT STAR FROM MOVIES
				WHERE VOTES>25000
				GROUP BY STAR
                HAVING AVG(SCORE) > 8.5)
ORDER BY STAR;

