-- UNION
SELECT * FROM person1 AS T1
UNION
SELECT * FROM PERSON2 AS T2;

-- UNION2
SELECT * FROM person1 AS T1
UNION ALL
SELECT * FROM PERSON2 AS T2;

-- INTERSECT
SELECT * FROM person1 AS T1
INTERSECT
SELECT * FROM PERSON2 AS T2;

-- EXCEPT
SELECT * FROM person1 AS T1
EXCEPT
SELECT * FROM PERSON2 AS T2;
