SELECT * FROM MOVIES;
-- MOVIE WITH HGHEST RATING
SELECT * FROM MOVIES
WHERE SCORE = (SELECT MAX(SCORE) FROM MOVIES);

-- MOVIE WITH HIGHEST PROFIT
SELECT NAME,(GROSS-BUDGET) AS 'PROFIT' FROM MOVIES
WHERE GROSS-BUDGET = (SELECT MAX(GROSS-BUDGET) FROM MOVIES);

-- MOVIES WITH ABOVE AVG RATING
SELECT COUNT(*) AS 'NUMBER OF MOVIES' FROM MOVIES
WHERE SCORE > (SELECT AVG(SCORE) FROM MOVIES);

-- HIGHEST RATED MOVIE OF YEAR 2000
SELECT * FROM MOVIES 
WHERE YEAR = 2000 AND SCORE = (SELECT MAX(SCORE) FROM MOVIES
								WHERE YEAR = 2000);
                                
SELECT AVG(VOTES) FROM MOVIES;

-- MOVIE WITH VOTES GREATER THAN AVERAGE VOTES AND HIGHEST RATING
SELECT * FROM MOVIES
WHERE VOTES > (SELECT AVG(VOTES) FROM MOVIES) AND SCORE = (SELECT MAX(SCORE) FROM MOVIES);

