-- FIND THE MOST PROFITABLE MOVIE OF EACH YEAR
SELECT * FROM MOVIES;

SELECT * FROM MOVIES
WHERE (YEAR,GROSS-BUDGET) IN (SELECT YEAR, MAX(GROSS - BUDGET)
								FROM MOVIES
								group by YEAR)
ORDER BY YEAR DESC;

-- FIND HIGHEST RATED MOVIE OF EACH GENRE
SELECT * FROM MOVIES
WHERE (GENRE,SCORE) IN (SELECT GENRE, MAX(SCORE) FROM MOVIES
						WHERE VOTES > 25000
						GROUP BY GENRE)
AND VOTES > 25000
ORDER BY YEAR;

-- FIND THE HIGHEST GROSSING MOVIES OF TOP STAR/DIRECTOR COMBO IN TERMS OF TOTAL GROSS INCOME 
WITH BEST_COMBO AS (SELECT STAR,DIRECTOR, MAX(GROSS)
					FROM MOVIES
					GROUP BY STAR,DIRECTOR
					ORDER BY SUM(GROSS) DESC
					LIMIT 5
)
SELECT * FROM MOVIES
WHERE (STAR,DIRECTOR,GROSS) IN (SELECT * FROM BEST_COMBO)
ORDER BY GROSS DESC;
